### PR TITLE
Update declaration file to match what React expects for onChange

### PR DESCRIPTION
**Pull request by Conrad2134**
I started using this and had a tiny conflict with what React expected for an onChange signature, so I made this update. I'm still pretty green with TS, but I think it's right? At least it doesn't complain at me anymore.

### CODE REVIEW

**Comment by Conrad2134** [comment]
Sorry, Prettier ruined the style! I'll fix it.

**Comment by Conrad2134** [comment]
> Sorry, Prettier ruined the style! I'll fix it.

Fixed.

**Comment by jamiebuilds** [comment]
Oops

**Comment by Alex-Ferreli** [comment]
This issue seems fixed but the last npm version isn't it. Could you do a publish please?

**Comment by zamarawka** [comment]
@jamiebuilds I faced with this problem. Any news about new npm release?

**Pull request merged**
